source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'OpenSSL', :git => 'https://github.com/bither/OpenSSL.git', :branch => 'master'
pod 'FMDB', '~> 2.3'
pod 'Reachability', '~> 3.1.1'
pod 'CocoaLumberjack', '~> 1.9.1'